apiVersion: skaffold/v2beta6
kind: Config

profiles:
  - name: test
    activation:
      - command: test
    build:
      artifacts:
        - image: uk.icr.io/prometeo-cluster/mqttclient
    deploy:
      helm:
        releases:
          - name: mqttclient
            chartPath: chart/mqttclient
            artifactOverrides:
              mqttclient:
                image:
                  repository: uk.icr.io/prometeo-cluster/mqttclient
            overrides:
              mqttclient:
                namespace: test
  - name: default
    activation:
      - command: default
    build:
      artifacts:
        - image: uk.icr.io/prometeo-cluster/mqttclient
    deploy:
      helm:
        releases:
          - name: mqttclient
            chartPath: chart/mqttclient
            artifactOverrides:
              mqttclient:
                image:
                  repository: uk.icr.io/prometeo-cluster/mqttclient
